addSbtPlugin("org.scalameta"         % "sbt-scalafmt" % "2.4.5")
addSbtPlugin("com.eed3si9n"          % "sbt-assembly" % "1.1.0")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"   % "7.4.0")
addSbtPlugin("au.com.onegeek"        % "sbt-dotenv"   % "2.1.204")
//addSbtPlugin("ph.samson" % "sbt-groovy" % "0.2.0")
